spring:
  application:
    name: clubhouseCRM
  contextPath: /
  mvc:
    view:
      suffix: .jsp
  session:
    store-type: jdbc
  jackson:
    serialization.INDENT_OUTPUT: true
  h2:
    console:
      enabled: true
      path: /console
  jpa:
    properties:
      hibernate:
        connection.charSet: UTF-8
        hbm2ddl.import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
security:
  basic:
    authorize-mode: none
  ignored:
  - /**
        # TODO enable security on unit tests
