spring:
  application:
    name: clubhouseCRM
  contextPath: /
  mvc:
    view:
      suffix: .jsp
  session:
    store-type: jdbc
  jackson:
    serialization.INDENT_OUTPUT: true
  h2:
    console:
      enabled: true
      path: /console
  jpa:
    properties:
      hibernate:
        connection.charSet: UTF-8
        hbm2ddl.import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
#
# Useful for debugging raw sql
#        show_sql: true
#        use_sql_comments: true
#        format_sql: true
#logging:
#  level:
#    org:
#      hibernate:
#        type: trace
