package edu.fhsu.csci466.clubhouse.crm;

import java.util.ArrayList;
import java.util.List;

import edu.fhsu.csci466.clubhouse.crm.service.model.Member;
import edu.fhsu.csci466.clubhouse.crm.service.model.services.Credential;

/**
 * @author scottKC
 *
 */
public class TestUtil
{
    /**
     * the number of members generated by the getMembers method
     */
    public static int MEMBER_COUNT = 20;

    /**
     * @return a list of members
     */
    public static List<Member> getMembers()
    {
        List<Member> members = new ArrayList<>();

        for ( long i = 1; i <= MEMBER_COUNT; ++i )
        {
            members.add( getMember( i ) );
        }

        return members;
    }

    /**
     * @param i
     * @return an initialized test member
     */
    public static Member getMember( final long i )
    {
        Credential c = new Credential();
        c.setCredentialId( i * 100 );
        c.setPassword( "secret" );
        c.setUserName( "user" + i );

        Member m = new Member();
        m.setMemberId( i );
        m.setName( "name" + i );
        m.setEmail( "m" + i + "@email.com" );
        m.setCredential( c );

        return m;
    }

    public static Member getMemberNoCredential( final long i )
    {
        Member m = getMember( i );
        m.setCredential( null );
        return m;
    }
}
